enum ACTION_TYPE {
  LOGIN = 'LOGIN',
  PROFILE = 'PROFILE',
  GET_PROJECTS = 'GET_PROJECTS',
  DELETE_PROJECT = 'DELETE_PROJECT',
  GET_QUANTITY_PROJECT = 'GET_QUANTITY_PROJECT',
  GET_TIMESHEET_STATISTIC_TASKS = 'GET_TIMESHEET_STATISTIC_TASKS',
  GET_TIMESHEET_STATISTIC_TEAMS = 'GET_TIMESHEET_STATISTIC_TEAMS',
}

export default ACTION_TYPE;
